### ISSUE TITLE
Rare exception saving system config

### ISSUE THREAD

**Issue by mattcasters** [mattcasters/kettle-environment#27]
2019/02/05 10:11:50 - General - ERROR (version 8.2.0.0-SNAPSHOT, build 8.2.0.0-SNAPSHOT from 2018-12-14 05.03.28 by kettle) : Error saving the environment system config:
2019/02/05 10:11:50 - General - ERROR (version 8.2.0.0-SNAPSHOT, build 8.2.0.0-SNAPSHOT from 2018-12-14 05.03.28 by kettle) : org.pentaho.metastore.api.exceptions.MetaStoreElementExistException: The specified element already exists with the same ID: 'system'
2019/02/05 10:11:50 - General - 	at org.pentaho.metastore.stores.xml.XmlMetaStore.createElement(XmlMetaStore.java:485)
2019/02/05 10:11:50 - General - 	at org.pentaho.metastore.persist.MetaStoreFactory.saveElement(MetaStoreFactory.java:520)
2019/02/05 10:11:50 - General - 	at org.kettle.env.config.EnvironmentConfigSingleton.saveConfig(EnvironmentConfigSingleton.java:37)
2019/02/05 10:11:50 - General - 	at org.kettle.env.spoon.EnvironmentHelper.switchEnvironment(EnvironmentHelper.java:94)
2019/02/05 10:11:50 - General - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019/02/05 10:11:50 - General - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019/02/05 10:11:50 - General - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019/02/05 10:11:50 - General - 	at java.lang.reflect.Method.invoke(Method.java:498)
2019/02/05 10:11:50 - General - 	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:313)
2019/02/05 10:11:50 - General - 	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
2019/02/05 10:11:50 - General - 	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
2019/02/05 10:11:50 - General - 	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
2019/02/05 10:11:50 - General - 	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
2019/02/05 10:11:50 - General - 	at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
2019/02/05 10:11:50 - General - 	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:545)
2019/02/05 10:11:50 - General - 	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:490)
2019/02/05 10:11:50 - General - 	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:402)
2019/02/05 10:11:50 - General - 	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
2019/02/05 10:11:50 - General - 	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
2019/02/05 10:11:50 - General - 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
2019/02/05 10:11:50 - General - 	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
2019/02/05 10:11:50 - General - 	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1381)
2019/02/05 10:11:50 - General - 	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7817)
2019/02/05 10:11:50 - General - 	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9179)
2019/02/05 10:11:50 - General - 	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:707)
2019/02/05 10:11:50 - General - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019/02/05 10:11:50 - General - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019/02/05 10:11:50 - General - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019/02/05 10:11:50 - General - 	at java.lang.reflect.Method.invoke(Method.java:498)
2019/02/05 10:11:50 - General - 	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)

**Comment by mattcasters** [comment]
Once it happens it keeps happening.  Perhaps we can load the old version, save under "old_system", delete the system and then resume regular save, something like that.

**Comment by mattcasters** [comment]
Still happened to me today. Must be something very rare.

**Comment by mattcasters** [comment]
No longer caching MetaStore and MetaStoreFactory.  I suspect something is cleared up automatically somewhere.
